### PR TITLE
Adding Japanese Whitepaper in LaTeX format

### PR DESCRIPTION
**Pull request by KeiCrypto**
Hi, here is Japanese whitepaper in LaTeX format.
Thanks!

### CODE REVIEW

**Comment by aching** [comment]
Hi @KeiCrypto , thanks for working on this! Looking forward to getting an amazing Japanese translation in the repo! Does it build for you in overleaf?  I'm getting an error building it with xetex

<*> main.tex
            
*** (job aborted, no legal \end found)

How are you building it?

**Comment by KeiCrypto** [comment]
Hi Avery,
Yes it was build in overleaf.
I built in TeXShop(MacTeX), then I couldn't Typeset properly with Japanese letters, so I built it again in overleaf.
I've just added original version which was build by TeXShop as 'main.tex' (I named previous one 'main overleaf.tex'), could you please check it?
Thanks a lot ;)

Kei

**Comment by aching** [comment]
@KeiCrypto I think the issue is that the first \begin{comment} doesn't have an \end{comment} in main.tex. I added it on line 53 and things seem fine, but I don't know Japanese and if that's your intention. =)

Anyway, look forward to hearing back from you. If not, I can merge what you have an we can continue to edit it further! Let me know how you'd like to proceed.

Thanks again!

**Comment by KeiCrypto** [comment]
@aching Hi Avery,
Thanks so much for your correction :)
Please merge it and continue to edit it further.

Thank you very much again for your kindness!

**Review by aching — APPROVED** [review]
As per @KeiCrypto 's comment, let's just get this committed.

There are a few issues that we can sort out after the initial commit - such as the extra main overleaf.txt, main.log, and adding a comment for main.tex to close the initial comment.

**Pull request merged**
